### PR TITLE
Add Londroid march meet up event

### PR DESCRIPTION
**Pull request by AndrewJack**
http://www.meetup.com/android/events/227013108/

Will rebase after #152 has been merged

### CODE REVIEW

**Comment by sboundy** [comment]
:+1:

**Comment by AndrewJack** [comment]
Rebased changes - ready for merging @sboundy

**Comment by craggy2593** [comment]
@AndrewJack Just before that, in your description, it reads 'Sky will be in speaking...' - Don't think it needs the 'in' there.

Aside from that, :shipit:

**Comment by AndrewJack** [comment]
@craggy2593 fixed :tada:

**Pull request merged**
